baseURL = "https://sigongzi.github.io/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
theme = "stack"
paginate = 5
title = "æµ·é¸¥çš„ç å¤´"

[languages.zh-cn]
languageName = "ä¸­æ–‡"
title = "æµ·é¸¥çš„ç å¤´"

[params]
mainSections = ["post"]
featuredImageField = "image"
rssFullContent = true

[params.sidebar]
emoji = "ğŸŸ"
subtitle = "æ¥è¿™é‡Œæ•´ç‚¹è–¯æ¡"

[params.sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[params.series]
enabled = true
orderByWeight = true  # å¯ç”¨ series_weight æ’åº

[params.article]
math = true
toc = true
readingTime = true

# é¦–é¡µå°éƒ¨ä»¶é…ç½®
[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"
[params.widgets.homepage.params]
limit = 5

[[params.widgets.homepage]]
type = "categories"
[params.widgets.homepage.params]
limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"
[params.widgets.homepage.params]
limit = 20

# å¯¼èˆªèœå•é…ç½®
[[menu.main]]
identifier = "home"
name = "é¦–é¡µ"
url = "/"
weight = -100
[menu.main.params]
icon = "home"


[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[markup.highlight]
noClasses = false
lineNos = true
style = "dracula"